# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f202d2fde3c8f11ec9090294028c5ef965f690f0ddb013e7d1eb80d5cf64f26d1bfa7c4b6bee72440380efe28d467ced9362fd9cfe66e0776a9b9f8a471b382

test:
  secret_key_base: 6a3352cd09901af8551be0bfb0688ee31959d5ea136ce13e10fa446776e3543eb65c3723e1efafdcdc5f5fd3310e9197f4d596e955092091b958b3b8a429407c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
